name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  macOSBuild:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: brew install glfw
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  linuxBuild:

    runs-on: ubuntu-latest

    steps:
    - uses: sersoft-gmbh/SwiftyActions@v1
      with:
        release-version: 5.3
    - uses: actions/checkout@v2
    - run: sudo apt-get install libglfw3
    - run: sudo apt-get install libglfw3-dev
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v