name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: brew install glfw
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
